### ISSUE TITLE
Servce LoadBalancer on-premise

### ISSUE THREAD

**Issue by gulecroc** [scraly/understanding-kubernetes-in-a-visual-way#1]
Hello Aurélie,

Thank's again for the book !

On Service LoadBalancer page, can you add a comment like Ingress to mention that for on-premise solution, it is implementend outside the cluster by a third party, like MetalLB ?

Best regards.
Guillaume

**Comment by scraly** [comment]
Good point, thanks :) 

(I hope the next time i'll receive the notification :-D)

**Comment by scraly** [comment]
fixed in 2.0.4
