### ISSUE TITLE
PodSecurityPolicy successor

### ISSUE THREAD

**Issue by gulecroc** [scraly/understanding-kubernetes-in-a-visual-way#2]
Hello Aurélie,

On PodSecurityPolicy page, you indicate that it is removed in 1.25, but you does not mention the successor, until the page Kubernetes 1.21.
It's a bit confusing at first read :)

Best regards,
Guillaume

**Comment by scraly** [comment]
Hi,

yes you're right, I plan to add it in the next version: 2.0.4 :-).

**Comment by scraly** [comment]
I added the migration guide info
fixed in 2.0.4
