### ISSUE TITLE
ReclaimPolicy : status released for retain instead of delete ?

### ISSUE THREAD

**Issue by tpoindessous** [scraly/understanding-kubernetes-in-a-visual-way#8]
Hi

in v2.0.0 of the book, page 125 , reclaim Policy

the last phrase about released status seems belonging to the Retain option instead of the Delete option , don’t you think ?

thanks 🙏

**Comment by scraly** [comment]
indeed I agree :)
thanks!

**Comment by scraly** [comment]
fixed in 2.0.4
